### ISSUE TITLE
createCheckoutSession call failing

### ISSUE THREAD

**Issue by shivkanthb** [ynnoj/next-stripe#24]
![Screen Shot 2021-02-23 at 2 16 36 AM](https://user-images.githubusercontent.com/3232159/108829779-73420380-757d-11eb-80e8-c37aaba2e5cb.png)

The createCheckoutSession call is returning a 401. I double checked  and the keys are all properly set. 
Any idea what might be happening here? 

Here's what my session object looks like
```
const session = await createCheckoutSession({
        success_url: window.location.href,
        cancel_url: window.location.href,
        line_items: [
          {
            price: <price_id>,
            quantity: 1,
          },
        ],
        payment_method_types: ["card"],
        mode: "subscription",
      });
```

**Comment by ynnoj** [comment]
@shivkanthb You need to log the error thrown [here](https://github.com/ynnoj/next-stripe/blob/cfaf335507021652cc734cdb33b3dd43467177f7/src/lib/fetcher.js#L8-L15). That will give you some more context.

Wrap the `createCheckoutSession` call in a try/catch block.

**Comment by shivkanthb** [comment]
Thanks for the super fast response @ynnoj! Looks like the key is not sent in the request? I have it configured on my [...nextstripe.js] endpoint.

<img width="501" alt="Screen Shot 2021-02-23 at 12 06 03 PM" src="https://user-images.githubusercontent.com/3232159/108901273-84b3fb80-75cf-11eb-9b28-261ef63acfce.png">

**Comment by ynnoj** [comment]
What version are you using? As of [`v1.0.0-beta.9`](https://github.com/ynnoj/next-stripe/releases/tag/v1.0.0-beta.9) the options key is called `stripe_key`.

```js
import NextStripe from 'next-stripe'

export default NextStripe({
  stripe_key: process.env.STRIPE_RESTRICTED_KEY
})
```

**Comment by shivkanthb** [comment]
Just noticed that right now after looking at [this](https://github.com/ynnoj/next-stripe/issues/24#issuecomment-784326155) I had the beta.8 version. Thanks for checking! love the package 💯
