### ISSUE TITLE
Support for recurring payment?

### ISSUE THREAD

**Issue by tadinski** [ynnoj/next-stripe#27]
As I understand, currently, recurring payments are not supported? I get an error.

**Comment by philohelp** [comment]
It seems to be working here (at least in test mode). In createCheckoutSession make sure you updated the mode field with "subscription".

**Comment by ynnoj** [comment]
@tadinski You can create [subscription mode](https://stripe.com/docs/billing/subscriptions/build-subscriptions?ui=checkout) Checkout Sessions with the library, yep. However there's no direct support for the subscriptions API.
