### ISSUE TITLE
Cannot find module 'next-stripe'

### ISSUE THREAD

**Issue by caioOlivera** [ynnoj/next-stripe#30]
I don't know if this is a bug or if I'm doing something wrong (it could it could possibly be since Im learning React/Next) but Next does not seem to find the library. Im running the command line "yarn add next-stripe@beta", the next-stripe folder is being added in the modules folder and the lock file is being updated with the new dependency and when I try to import { createCheckoutSession } from "next-stripe/client" I get the "Could not find a declaration file for module" error. Could use some help.

**Comment by birdboy307** [comment]
I'm getting the same error but this repo doesn't seem to be too active hopefully it does sometime soon for some help

**Comment by ynnoj** [comment]
If you're using the library in a Typescript project, it'll error as there's no type definitions (yet). 

To remedy this you can just declare the module locally in your own project:
```ts
// next-stripe.d.ts
declare module 'next-stripe';
```

I'm working on adding some typings for the library

**Comment by birdboy307** [comment]
With my issue was using JavaScript any suggestions

**Comment by ynnoj** [comment]
@birdboy307 I'm not able to replicate this issue in a JavaScript project. Can you provide a reproduction?
